final Map<String, String> bibleBooksLatin = {
  "Genesis": "Genesis",
  "Exodus": "Exodus",
  "Leviticus": "Leviticus",
  "Numbers": "Numeri",
  "Deuteronomy": "Deuteronomium",
  "Joshua": "Iosue",
  "Judges": "Judices",
  "Ruth": "Ruth",
  "1 Samuel": "1Regum",
  "2 Samuel": "2Regum",
  "1 Kings": "3Regum",
  "2 Kings": "4Regum",
  "1 Chronicles": "1Paralipomenon",
  "2 Chronicles": "2Paralipomenon",
  "Ezra": "Esdras",
  "Nehemiah": "Nehemias",
  "Tobit": "Tobias",
  "Judith": "Iudith",
  "Esther": "Esther",
  "Job": "Iob",
  "Psalms": "Psalmi",
  "Proverbs": "Proverbia",
  "Ecclesiastes": "Ecclesiastes",
  "Song of Solomon": "Canticum Canticorum",
  "Wisdom": "Sapientia",
  "Sirach": "Ecclesiasticus",
  "Isaiah": "Isaias",
  "Jeremiah": "Ieremias",
  "Lamentations": "Lamentationes",
  "Baruch": "Baruch",
  "Ezekiel": "Ezechiel",
  "Daniel": "Daniel",
  "Hosea": "Osee",
  "Joel": "Ioel",
  "Amos": "Amos",
  "Obadiah": "Abdias",
  "Jonah": "Ionas",
  "Micah": "Micheas",
  "Nahum": "Nahum",
  "Habakkuk": "Habacuc",
  "Zephaniah": "Sophonias",
  "Haggai": "Aggaeus",
  "Zechariah": "Zacharias",
  "Malachi": "Malachias",
  "Matthew": "Matthæus",
  "Mark": "Marcus",
  "Luke": "Lucas",
  "John": "Joannes",
  "Acts": "Actus Apostolorum",
  "Romans": "Ad Romanos",
  "1 Corinthians": "1Corinthios",
  "2 Corinthians": "2Corinthios",
  "Galatians": "Ad Galatas",
  "Ephesians": "Ad Ephesios",
  "Philippians": "Ad Philippenses",
  "Colossians": "Ad Colossenses",
  "1 Thessalonians": "1Thessalonicenses",
  "2 Thessalonians": "2Thessalonicenses",
  "1 Timothy": "1Timotheum",
  "2 Timothy": "2Timotheum",
  "Titus": "Ad Titum",
  "Philemon": "Ad Philemonem",
  "Hebrews": "Ad Hebraeos",
  "James": "Iacobus",
  "1 Peter": "1Petrum",
  "2 Peter": "2Petrum",
  "1 John": "1Joannis",
  "2 John": "2Joannis",
  "3 John": "3Joannis",
  "Jude": "Iudas",
  "Revelation": "Apocalypsis"
};
